services:
  app-staging:
    image: fullfrontend/php-fpm:latest
    container_name: retaia-core-app-staging
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/RETAIA:/var/local/RETAIA
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      DATABASE_URL: postgresql://app:app@database-staging:5432/app_staging?serverVersion=16&charset=utf8
      APP_INGEST_WATCH_PATH: /var/local/RETAIA/INBOX
    depends_on:
      database-staging:
        condition: service_healthy
    tty: true
    stdin_open: true

  caddy-staging:
    image: caddy:2-alpine
    container_name: retaia-core-caddy-staging
    depends_on:
      app-staging:
        condition: service_started
    ports:
      - "${RETAIA_STAGING_HTTP_PORT:-18081}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/Caddyfile.staging:/etc/caddy/Caddyfile:ro

  database-staging:
    image: postgres:16-alpine
    container_name: retaia-core-db-staging
    environment:
      POSTGRES_DB: app_staging
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "app_staging", "-U", "app"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - "${RETAIA_STAGING_DB_PORT:-15433}:5432"
    volumes:
      - ./docker/db-data-staging:/var/lib/postgresql/data
