version: 2.1

jobs:
  test:
    docker:
      - image: cimg/php:8.3
    environment:
      APP_ENV: test
      APP_DEBUG: "1"
      COMPOSER_CACHE_DIR: /home/circleci/.composer/cache
    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-

      - run:
          name: Validate composer.json
          command: composer validate --strict

      - run:
          name: Install dependencies
          command: composer install --no-interaction --prefer-dist --optimize-autoloader

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - /home/circleci/.composer/cache
            - vendor

      - run:
          name: Run test suite
          command: composer test

workflows:
  ci:
    jobs:
      - test

